[project]
name = "ventoy-ng-cpio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fnrir", email = "fnr1r0@protonmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ventoy-ng-cpio = "ventoy_ng_cpio:main"

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
