line-length = 79

[lint]
select = [
    "YTT",  # flake8-2020
    "BLE",  # flake8-blind-except
    "B",    # flake8-bugbear
    "A",    # flake8-builtins
    "COM",  # flake8-commas
    "C4",   # flake8-comprehensions
    "EXE",  # flake8-executable
    "FIX",  # flake8-fixme
    "PIE",  # flake8-pie
    "Q",    # flake8-quotes
    "RSE",  # flake8-raise
    "SLF",  # flake8-self
    "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    "TC",   # flake8-type-checking
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "I",    # isort
    "N",    # pep8-naming
    "PERF", # perflint
    "E", "W",   # pycodestyle
    "F",    # pyflakes
    "PL",   # pylint
    "UP",   # pyupgrade
    "FURB", # refurb
    "RUF",  # ruff-specific rules
    "TRY",  # tryceratops
]
ignore = [
    # https://github.com/astral-sh/ruff/issues/9216
    # sadge :(
    "COM812",
    # I prefer Rust-style Option<T>
    "UP045",
]
