name = "busybox"
#version = "1.36.1"
version = "1.32.0"
id = "{name}"
url = "https://busybox.net/downloads/{name}-{version}.tar.bz2"
hash = "sha256:c35d87f1d04b2b153d33c275c2632e40d388a88f19a9e71727e0bbbff51fe689"
extracted_name = "{name}-{version}"
