name = "device-mapper"
version = "1.02.28"
id = "{name}"
url = "ftp://sourceware.org/pub/dm/{name}.{version}.tgz"
hash = "sha256:24c7887fe896325a6cdc86b8beeb0d9c2de8b1c4cb20f53c2dc8f90963fc39bf"
extracted_name = "{name}.{version}"
