name = "libfuse2"
version = "2.9.9"
id = "{name}"
url = "https://github.com/libfuse/libfuse/releases/download/fuse-{version}/fuse-{version}.tar.gz"
hash = "sha256:d0e69d5d608cc22ff4843791ad097f554dd32540ddc9bed7638cc6fea7c1b4b5"
extracted_name = "fuse-{version}"
