name = "lz4"
version = "1.10.0"
id = "{name}"
url = "https://github.com/lz4/{name}/releases/download/v{version}/{name}-{version}.tar.gz"
hash = "sha256:537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b"
extracted_name = "{name}-{version}"
