name = "lzo"
version = "2.10"
id = "{name}"
url = "https://www.oberhumer.com/opensource/{name}/download/{name}-{version}.tar.gz"
hash = "sha256:c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072"
extracted_name = "{name}-{version}"
