name = "squashfs"
version = "4.4"
id = "{name}"
url = "https://netix.dl.sourceforge.net/project/{name}/{name}/{name}{version}/{name}{version}.tar.gz"
hash = "sha256:a981b3f3f2054b5a2e658851a3c06a2460ad04a9a8a645e0afe063a63fdbb07e"
extracted_name = "{name}{version}"
