name = "vblade"
version = "24"
id = "{name}"
url = "https://github.com/OpenAoE/{name}/archive/refs/tags/{name}-{version}.tar.gz"
hash = "sha256:8ef4129d101d26065294692dc5224bc430f553c8640de71207a031d4b4204bdb"
extracted_name = "{name}-{name}-{version}"
