name = "xz-embedded"
version = "2024-12-30"
id = "{name}"
url = "https://github.com/tukaani-project/{name}/archive/refs/tags/v{version}.tar.gz"
filename = "{name}-{version}.tar.gz"
hash = "sha256:ee12fa8c49c9c0ef4a144af4234d2530d786c1ce14247a7d5fc92a946628977d"
extracted_name = "{name}-{version}"
