name = "xz"
version = "5.6.4"
id = "{name}"
url = "https://github.com/tukaani-project/{name}/releases/download/v{version}/{name}-{version}.tar.xz"
hash = "sha256:829ccfe79d769748f7557e7a4429a64d06858e27e1e362e25d01ab7b931d9c95"
extracted_name = "{name}-{version}"
