name = "zlib"
version = "1.3.1"
id = "{name}"
url = "https://github.com/madler/{name}/releases/download/v{version}/{name}-{version}.tar.xz"
hash = "sha256:38ef96b8dfe510d42707d9c781877914792541133e1870841463bfa73f883e32"
extracted_name = "{name}-{version}"
