name = "zstd"
version = "1.5.7"
id = "{name}"
url = "https://github.com/facebook/{name}/releases/download/v{version}/{name}-{version}.tar.zst"
hash = "sha256:5b331d961d6989dc21bb03397fc7a2a4d86bc65a14adc5ffbbce050354e30fd2"
extracted_name = "{name}-{version}"
