name = "ventoy-cpio"

[[target]]
name = "system/x86_64"
triple = "x86_64-linux"
suffix = "64"

[[target]]
name = "system/i386"
triple = "i386-linux"
suffix = "32"

[[target]]
name = "system/aarch64"
triple = "aarch64-linux"
suffix = "aa64"

[[target]]
name = "system/mips64el"
tuple = "mips64el-linux"
suffix = "m64e"

[[target]]
name = "output/x86"
subtargets = ["system/x86_64", "system/i386"]

[[target]]
name = "output/arm64"
subtargets = ["system/aarch64"]

[[target]]
name = "output/mips64"
subtargets = ["system/mips64el"]

[[sources]]
name = "busybox"
#version = "1.36.1"
version = "1.32.0"
id = "{name}"
url = "https://busybox.net/downloads/{name}-{version}.tar.bz2"
hash = "sha256:c35d87f1d04b2b153d33c275c2632e40d388a88f19a9e71727e0bbbff51fe689"
extracted_name = "{name}-{version}"

[[sources]]
name = "device-mapper"
version = "1.02.28"
id = "{name}"
url = "ftp://sourceware.org/pub/dm/{name}.{version}.tgz"
hash = "sha256:24c7887fe896325a6cdc86b8beeb0d9c2de8b1c4cb20f53c2dc8f90963fc39bf"
extracted_name = "{name}.{version}"

[[sources]]
name = "lunzip"
version = "1.11"
id = "{name}"
url = "https://download.savannah.gnu.org/releases/lzip/{name}/{name}-{version}.tar.gz"
hash = "sha256:21ad5f051cc516c5fc05cb6dfc9bb66737d9810cfa9349709e42c545eb1bf8a7"
extracted_name = "{name}-{version}"

[[sources]]
name = "lz4"
version = "1.10.0"
id = "{name}"
url = "https://github.com/lz4/{name}/releases/download/v{version}/{name}-{version}.tar.gz"
hash = "sha256:537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b"
extracted_name = "{name}-{version}"

[[sources]]
name = "smallz4"
version = "1.5"
id = "{name}"
url = "https://create.stephan-brumme.com/{name}/{name}cat.c"
hash = "sha256:464a0c0f4b9962df73d863fab080c1a6f354444ef9f40ba2edeebe1d852cf44e"

[[sources]]
name = "lzo"
version = "2.10"
id = "{name}"
url = "https://www.oberhumer.com/opensource/{name}/download/{name}-{version}.tar.gz"
hash = "sha256:c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072"
extracted_name = "{name}-{version}"

[[sources]]
name = "squashfs"
version = "4.4"
id = "{name}"
url = "https://netix.dl.sourceforge.net/project/{name}/{name}/{name}{version}/{name}{version}.tar.gz"
hash = "sha256:a981b3f3f2054b5a2e658851a3c06a2460ad04a9a8a645e0afe063a63fdbb07e"
extracted_name = "{name}{version}"

[[sources]]
name = "vblade"
version = "24"
id = "{name}"
url = "https://github.com/OpenAoE/{name}/archive/refs/tags/{name}-{version}.tar.gz"
hash = "sha256:8ef4129d101d26065294692dc5224bc430f553c8640de71207a031d4b4204bdb"
extracted_name = "{name}-{name}-{version}"

[[sources]]
name = "xz"
version = "5.6.4"
id = "{name}"
url = "https://github.com/tukaani-project/{name}/releases/download/v{version}/{name}-{version}.tar.xz"
hash = "sha256:829ccfe79d769748f7557e7a4429a64d06858e27e1e362e25d01ab7b931d9c95"
extracted_name = "{name}-{version}"

[[sources]]
name = "xz-embedded"
version = "2024-12-30"
id = "{name}"
url = "https://github.com/tukaani-project/{name}/archive/refs/tags/v{version}.tar.gz"
filename = "{name}-{version}.tar.gz"
hash = "sha256:ee12fa8c49c9c0ef4a144af4234d2530d786c1ce14247a7d5fc92a946628977d"
extracted_name = "{name}-{version}"

[[sources]]
name = "zlib"
version = "1.3.1"
id = "{name}"
url = "https://github.com/madler/{name}/releases/download/v{version}/{name}-{version}.tar.xz"
hash = "sha256:38ef96b8dfe510d42707d9c781877914792541133e1870841463bfa73f883e32"
extracted_name = "{name}-{version}"

[[sources]]
name = "zstd"
version = "1.5.7"
id = "{name}"
url = "https://github.com/facebook/{name}/releases/download/v{version}/{name}-{version}.tar.zst"
hash = "sha256:5b331d961d6989dc21bb03397fc7a2a4d86bc65a14adc5ffbbce050354e30fd2"
extracted_name = "{name}-{version}"

[[components]]
name = "busybox-ash"
target_set = "system"
sources = ["busybox"]
build_file = "components/busybox/build.py"

[[components]]
name = "busybox-full"
target_set = "system"
sources = ["busybox"]
build_file = "components/busybox/build.py"

[[components]]
name = "busybox-hexdump"
target_set = "system"
sources = ["busybox"]
build_file = "components/busybox/build.py"

[[components]]
name = "busybox-xzcat"
target_set = "system"
sources = ["busybox"]
build_file = "components/busybox/build.py"

[[components]]
name = "device-mapper"
target_set = "system"
sources = ["device-mapper"]

[[components]]
name = "lunzip"
target_set = "system"
sources = ["lunzip"]

[[components]]
name = "lz4"
target_set = "system"
sources = ["lz4"]

[[components]]
name = "lzo"
target_set = "system"
sources = ["lzo"]

[[components]]
name = "smallz4"
target_set = "system"
sources = ["smallz4"]

[[components]]
name = "vblade"
target_set = "system"
sources = ["vblade"]

[[components]]
name = "xz"
target_set = "system"
sources = ["xz"]

[[components]]
name = "xz-embedded"
target_set = "system"
sources = ["xz-embedded"]

[[components]]
name = "zlib"
target_set = "system"
sources = ["zlib"]

[[components]]
name = "zstd"
target_set = "system"
sources = ["zstd"]

[[components]]
name = "squashfs"
target_set = "system"
sources = ["squashfs"]
deps = ["lz4", "lzo", "xz", "zlib", "zstd"]

[[components]]
name = "rd-stage2-tools"
target_set = "system"
deps = [
    "busybox-full",
    "device-mapper",
    "lunzip",
    "smallz4",
    "squashfs",
    "vblade",
    "zlib",
    "zstd",
]

[[components]]
name = "rd-stage2"
target_set = "output"
deps = ["rd-stage2-tools"]
build_file = "components/cpio/build.py"
build_args.cpio_dir = "."
build_args.cpio_files = "tool"
build_args.cpio_target = "tool.cpio.xz"

[[components]]
name = "rd-stage1-tools"
target_set = "system"
deps = ["busybox-ash", "busybox-xzcat", "xz-embedded"]

[[components]]
name = "arch-ramdisks"
target_set = "output"
deps = ["rd-stage2", "rd-stage1-tools"]
build_file = "components/cpio/build.py"
build_args.cpio_dir = "ramdisk"
build_args.cpio_files = "."
build_args.cpio_target = "ventoy_{target}.cpio"

[[components]]
name = "base"

[[components]]
name = "main"
deps = ["base", "arch-ramdisks"]
