name = "rd-stage2-tools"
target_set = "system"
deps = [
    "device-mapper",
    "smallz4",
    # "vtoytool",
]

[[per_target]]
# anything except mips64el
rule = "^(?!mips64el).*$"
deps = [
    "lunzip",
    "squashfs",
    "vblade",
    # "vtoy_fuse_iso",
    "zlib",
    "zstd",
]
